web:
  image: nginx:latest
  container_name: nginx_my-ip
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./code:/code
